language: scala
sudo: false
addons:
  apt:
    packages:
    - numactl
    - libnuma1
    - libnuma-dev
    - libnuma-dbg
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt
  - $HOME/ssl
  - $HOME/mongodb-linux-x86_64-2.6.12
  - $HOME/mongodb-linux-x86_64-amazon-3.2.8
scala:
- 2.11.7
- 2.10.5
jdk:
- oraclejdk8
- oraclejdk7
sudo: false
before_install:
- ./.travis_scripts/beforeInstall.sh $TRAVIS_SCALA_VERSION $MONGO_SSL
script: ./.travis_scripts/retry.sh 3 ./.travis_scripts/validate.sh
after_success: ./.travis_scripts/afterSuccess.sh
env:
  matrix:
  - MONGO_SSL=true
  - MONGO_SSL=false
