language: scala
script: ./.travis_scripts/validate.sh
scala:
- 2.11.6
jdk:
- oraclejdk7
before_install:
- sudo ./.travis_scripts/beforeInstall.sh $TRAVIS_SCALA_VERSION $MONGO_SSL
script: ./.travis_scripts/validate.sh
after_success: ./.travis_scripts/afterSuccess.sh
env:
- MONGO_SSL=true
